### PR TITLE
Create frontend

### PR DESCRIPTION
**Pull request by Dmium**

### CODE REVIEW

**Comment by Dmium** [comment]
[Setup Vue Frontend](https://trello.com/c/rbMy3lhC/8-setup-vue-frontend)

**Review by teska77 — COMMENTED** [review]
good shit 👍

**Review by teska77 — APPROVED** [review]
very good shit 💯

**Review by kchokanov — APPROVED** [review]
</3 Why doesn't WLS come with Docker pre-set up...

**Pull request merged**
