### PR TITLE
Infrastructure setup (You don't want to know)

### PR DESCRIPTION
**Pull request by Dmium**

### CODE REVIEW

**Review by teska77 — APPROVED** [review]
You're right...

### **I don't**

**Review by kchokanov — APPROVED** [review]
He died for our sins

**Comment by Dmium** [comment]
[Terraform connected to digital ocean](https://trello.com/c/lzCFgNSI/15-terraform-connected-to-digital-ocean)

**Comment by Dmium** [comment]
[Full deployment to Digital Ocean](https://trello.com/c/0P3FVGdQ/16-full-deployment-to-digital-ocean)

**Comment by Dmium** [comment]
[Setup authentication to push and pull images to DigitalOcean](https://trello.com/c/xT3WoyoB/17-setup-authentication-to-push-and-pull-images-to-digitalocean)

**Comment by Dmium** [comment]
[Setup authentication to deploy and manage clusters](https://trello.com/c/lREj8lcD/18-setup-authentication-to-deploy-and-manage-clusters)

**Pull request merged**
